<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('history_customer_order_products', function (Blueprint $table) {
            $table->id();
            $table->foreignId('customer_id')->constrained()->cascadeOnUpdate()->restrictOnDelete();
            $table->foreignId('product_id')->constrained()->cascadeOnUpdate()->restrictOnDelete();
            $table->integer('all_order_times')->default(0);
            $table->integer('all_order_discount_times')->default(0);
            $table->integer('all_order_free_delivery_times')->default(0);
            $table->integer('all_product_count')->default(0);
            $table->integer('all_product_discount_count')->default(0);
            $table->integer('all_product_free_delivery_count')->default(0);
            $table->integer('all_total_product_pay_price')->default(0);
            $table->integer('all_total_product_discount')->default(0);
            $table->integer('all_avg_product_pay_price')->default(0);
            $table->integer('all_avg_product_discount')->default(0);
            $table->integer('all_total_order_delivery')->default(0);
            $table->integer('all_total_product_delivery')->default(0);
            $table->integer('all_avg_product_delivery')->default(0);
            $table->text('all_order_first_date')->nullable();
            $table->text('all_order_last_date')->nullable();
            $table->text('all_purchase_date')->nullable();
            $table->text('all_purchase_day')->nullable();
            $table->integer('all_purchase_total_day')->default(0);
            $table->text('all_purchase_sequence_day')->nullable();
            $table->integer('all_purchase_avg_sequence_day')->default(0);
            $table->text('all_purchase_pressture_day')->nullable();
            $table->text('all_purchase_power_in_month')->nullable();
            $table->text('all_purchase_power_in_year')->nullable();
            $table->integer('pending_order_times')->default(0);
            $table->integer('pending_order_discount_times')->default(0);
            $table->integer('pending_order_free_delivery_times')->default(0);
            $table->integer('pending_product_count')->default(0);
            $table->integer('pending_product_discount_count')->default(0);
            $table->integer('pending_product_free_delivery_count')->default(0);
            $table->integer('pending_total_product_pay_price')->default(0);
            $table->integer('pending_total_product_discount')->default(0);
            $table->integer('pending_avg_product_pay_price')->default(0);
            $table->integer('pending_avg_product_discount')->default(0);
            $table->integer('pending_total_order_delivery')->default(0);
            $table->integer('pending_total_product_delivery')->default(0);
            $table->integer('pending_avg_product_delivery')->default(0);
            $table->text('pending_order_first_date')->nullable();
            $table->text('pending_order_last_date')->nullable();
            $table->text('pending_purchase_date')->nullable();
            $table->text('pending_purchase_day')->nullable();
            $table->integer('pending_purchase_total_day')->default(0);
            $table->text('pending_purchase_sequence_day')->nullable();
            $table->integer('pending_purchase_avg_sequence_day')->default(0);
            $table->text('pending_purchase_pressture_day')->nullable();
            $table->text('pending_purchase_power_in_month')->nullable();
            $table->text('pending_purchase_power_in_year')->nullable();
            $table->integer('delivered_order_times')->default(0);
            $table->integer('delivered_order_discount_times')->default(0);
            $table->integer('delivered_order_free_delivery_times')->default(0);
            $table->integer('delivered_product_count')->default(0);
            $table->integer('delivered_product_discount_count')->default(0);
            $table->integer('delivered_product_free_delivery_count')->default(0);
            $table->integer('delivered_total_product_pay_price')->default(0);
            $table->integer('delivered_total_product_discount')->default(0);
            $table->integer('delivered_avg_product_pay_price')->default(0);
            $table->integer('delivered_avg_product_discount')->default(0);
            $table->integer('delivered_total_order_delivery')->default(0);
            $table->integer('delivered_total_product_delivery')->default(0);
            $table->integer('delivered_avg_product_delivery')->default(0);
            $table->text('delivered_order_first_date')->nullable();
            $table->text('delivered_order_last_date')->nullable();
            $table->text('delivered_purchase_date')->nullable();
            $table->text('delivered_purchase_day')->nullable();
            $table->integer('delivered_purchase_total_day')->default(0);
            $table->text('delivered_purchase_sequence_day')->nullable();
            $table->integer('delivered_purchase_avg_sequence_day')->default(0);
            $table->text('delivered_purchase_pressture_day')->nullable();
            $table->text('delivered_purchase_power_in_month')->nullable();
            $table->text('delivered_purchase_power_in_year')->nullable();
            $table->integer('returned_order_times')->default(0);
            $table->integer('returned_order_discount_times')->default(0);
            $table->integer('returned_order_free_delivery_times')->default(0);
            $table->integer('returned_product_count')->default(0);
            $table->integer('returned_product_discount_count')->default(0);
            $table->integer('returned_product_free_delivery_count')->default(0);
            $table->integer('returned_total_product_pay_price')->default(0);
            $table->integer('returned_total_product_discount')->default(0);
            $table->integer('returned_avg_product_pay_price')->default(0);
            $table->integer('returned_avg_product_discount')->default(0);
            $table->integer('returned_total_order_delivery')->default(0);
            $table->integer('returned_total_product_delivery')->default(0);
            $table->integer('returned_avg_product_delivery')->default(0);
            $table->text('returned_order_first_date')->nullable();
            $table->text('returned_order_last_date')->nullable();
            $table->text('returned_purchase_date')->nullable();
            $table->text('returned_purchase_day')->nullable();
            $table->integer('returned_purchase_total_day')->default(0);
            $table->text('returned_purchase_sequence_day')->nullable();
            $table->integer('returned_purchase_avg_sequence_day')->default(0);
            $table->text('returned_purchase_pressture_day')->nullable();
            $table->text('returned_purchase_power_in_month')->nullable();
            $table->text('returned_purchase_power_in_year')->nullable();
            $table->integer('canceled_order_times')->default(0);
            $table->integer('canceled_order_discount_times')->default(0);
            $table->integer('canceled_order_free_delivery_times')->default(0);
            $table->integer('canceled_product_count')->default(0);
            $table->integer('canceled_product_discount_count')->default(0);
            $table->integer('canceled_product_free_delivery_count')->default(0);
            $table->integer('canceled_total_product_pay_price')->default(0);
            $table->integer('canceled_total_product_discount')->default(0);
            $table->integer('canceled_avg_product_pay_price')->default(0);
            $table->integer('canceled_avg_product_discount')->default(0);
            $table->integer('canceled_total_order_delivery')->default(0);
            $table->integer('canceled_total_product_delivery')->default(0);
            $table->integer('canceled_avg_product_delivery')->default(0);
            $table->text('canceled_order_first_date')->nullable();
            $table->text('canceled_order_last_date')->nullable();
            $table->text('canceled_purchase_date')->nullable();
            $table->text('canceled_purchase_day')->nullable();
            $table->integer('canceled_purchase_total_day')->default(0);
            $table->text('canceled_purchase_sequence_day')->nullable();
            $table->integer('canceled_purchase_avg_sequence_day')->default(0);
            $table->text('canceled_purchase_pressture_day')->nullable();
            $table->text('canceled_purchase_power_in_month')->nullable();
            $table->text('canceled_purchase_power_in_year')->nullable();
            $table->timestampsTz();
            $table->softDeletesTz();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('history_customer_order_products');
    }
};
